#include<iostream>
#include<string>
using namespace std;

/* to return kth character from a string generated from repeated opration on a string word="a"
  with the rule that word+= new string generated by a=b,b=c,...,z=a in new string and then added back to word 
  so k  grows exponentially with each iteration */

char kthCharacter(int k) {
        string word = "a";
        while((int)word.length()<=k){
          word+=generate(word);
        }
        
        return word[k-1];
    }
   string generate(const string& word){
    string gen = "";
     for(char c : word){
        gen += (c == 'z') ? 'a' : c + 1;

     }
     return gen;
}